#!/usr/bin/env bash
# stop-handoff-writer.sh — Stop event hook (Layer 0 element b)
# Job: Mechanically extract 7-field handoff and write .harness/handoff.md
# ZERO AI summary — jq + git only.
# Exit: always 0 (best-effort, never block session end)

set -uo pipefail
trap 'exit 0' ERR

# ── Graceful JSON parse with jq or python3 fallback ──────────────────────────
parse_session_id() {
  local payload="$1"
  if command -v jq >/dev/null 2>&1; then
    echo "${payload}" | jq -r '.session_id // "unknown"' 2>/dev/null || echo "unknown"
  else
    python3 -c "
import json, sys
try:
    d = json.loads(sys.argv[1])
    print(d.get('session_id', 'unknown'))
except Exception:
    print('unknown')
" "${payload}" 2>/dev/null || echo "unknown"
  fi
}

# ── Read stdin ────────────────────────────────────────────────────────────────
PAYLOAD=""
if [ -t 0 ]; then
  PAYLOAD="{}"
else
  PAYLOAD="$(cat 2>/dev/null || echo "{}")"
fi
[[ -z "${PAYLOAD}" ]] && PAYLOAD="{}"

# ── Skip if not a harness project ────────────────────────────────────────────
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HARNESS_DIR="${REPO_ROOT}/.harness"
if [[ ! -d "${HARNESS_DIR}" ]]; then
  exit 0
fi

# ── Collect fields ────────────────────────────────────────────────────────────
SESSION_ID="$(parse_session_id "${PAYLOAD}")"
TRIGGER="stop"
ENDED="$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date)"
COMMIT_HASH="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo "none")"
BRANCH="$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
MODIFIED_FILES="$(git -C "${REPO_ROOT}" status --porcelain 2>/dev/null || echo "(none)")"

# ── last_user_prompt: tail transcript JSONL ──────────────────────────────────
LAST_USER_PROMPT="(unavailable)"
TRANSCRIPT_DIR="${HOME}/.claude/projects"
if [[ -n "${SESSION_ID}" && "${SESSION_ID}" != "unknown" ]]; then
  # Claude Code stores transcripts as ~/.claude/projects/-<path>/<session_id>.jsonl
  TRANSCRIPT_FILE="$(find "${TRANSCRIPT_DIR}" -name "${SESSION_ID}.jsonl" 2>/dev/null | head -1)"
  if [[ -f "${TRANSCRIPT_FILE}" ]]; then
    LAST_USER_PROMPT="$(grep '"role":"user"' "${TRANSCRIPT_FILE}" 2>/dev/null | tail -1 | \
      python3 -c "
import sys, json
try:
    line = sys.stdin.read().strip()
    d = json.loads(line)
    content = d.get('content', '')
    if isinstance(content, list):
        parts = [p.get('text','') for p in content if isinstance(p, dict) and p.get('type')=='text']
        content = ' '.join(parts)
    print(str(content)[:500])
except Exception:
    print('(parse-error)')
" 2>/dev/null || echo "(parse-error)")"
  fi
fi

# ── Smart next_action: pull from latest handoff-SN-to-SN+1.md if P9 already wrote one ──
# Iron rule: Stop hook does ZERO AI summary. But if P9/CEO inline-wrote a handoff
# with a real next_action, defer to that authoritative source instead of TBD placeholder.
NEXT_ACTION="TBD-next-action-absent"
LATEST_AUTHORITATIVE="$(ls -1t "${HARNESS_DIR}"/handoff-S*-to-S*.md 2>/dev/null | head -1)"
if [[ -n "${LATEST_AUTHORITATIVE}" ]] && [[ -f "${LATEST_AUTHORITATIVE}" ]]; then
  EXTRACTED="$(awk '/^next_action:/{flag=1} flag{print; if(/"$/) exit}' "${LATEST_AUTHORITATIVE}" 2>/dev/null \
    | sed 's/^next_action: *//;s/^"//;s/"$//' | head -c 2000)"
  if [[ -n "${EXTRACTED}" ]] && [[ "${EXTRACTED}" != "TBD-"* ]]; then
    NEXT_ACTION="${EXTRACTED}"
    NEXT_ACTION_SOURCE="${LATEST_AUTHORITATIVE##*/}"
  fi
fi

# ── Write handoff.md ─────────────────────────────────────────────────────────
HANDOFF_FILE="${HARNESS_DIR}/handoff.md"

cat > "${HANDOFF_FILE}" <<HANDOFF_EOF
# Harness Handoff (auto-generated by stop-handoff-writer.sh)

## §fields

| Field | Value |
|-------|-------|
| session_id | ${SESSION_ID} |
| trigger | ${TRIGGER} |
| ended | ${ENDED} |
| commit_hash | ${COMMIT_HASH} |
| branch | ${BRANCH} |

## §modified_files

\`\`\`
${MODIFIED_FILES}
\`\`\`

## §last_user_prompt

\`\`\`
${LAST_USER_PROMPT}
\`\`\`

## §next_action

${NEXT_ACTION}

${NEXT_ACTION_SOURCE:+_(source: ${NEXT_ACTION_SOURCE} authoritative; this Stop hook deferred to it)_}

## §verification-checklist

- [ ] Read this handoff file before any Write/Edit/Bash in next session
- [ ] Run \`touch .harness/must-ack-done.flag\` after reading
- [ ] Verify commit_hash matches expected work
- [ ] Confirm branch is correct

## §transcript-tail

session_id: ${SESSION_ID}
ended: ${ENDED}
HANDOFF_EOF

echo "[stop-handoff-writer] handoff written → ${HANDOFF_FILE} (session=${SESSION_ID})" >&2
exit 0
